#!/bin/sh
#! -*-perl-*-
eval 'exec perl -x -wS $0 ${1+"$@"}' if 0;
#
# -*- mode: cperl; eval: (follow-mode 1); cperl-indent-level: 2; cperl-continued-statement-offset: 2 -*-
#

use strict;
use warnings;
use App::Keybeat;

App::Keybeat->new->run;

__END__

=head1 NAME

mailstate - script to get all "complete envelope" emails statistics
from sendmail log file and to put all that data into sqlite db file

=head1 SYNOPSIS

mailstate [-h|--help] [-l|--logfile I<FILE>] [-s|--saveto I<DIR>] [-e|--export I<FORMAT>]

=head1 DESCRIPTION

mailstate - script to get all "complete envelope" emails statistics

"complete envelope" is the envelope which has opening `from=<...' and
closing `to=<...' log file records

script is parsing log file provided with option I<-l> and groups
records by I<id>

log file expected is freebsd syslogd

results are written to sqlite db

sqlite db file .sqlite, by default, is placed at the same directory
log file processed resides, if I<-s> is set, than it is placed to that
directory.

db table scheme is:

	id              TEXT PRIMARY KEY
	ts              TEXT
	addr_fr         TEXT
	addr_to         TEXT
	size            NUM
	delay           TEXT
	xdelay          TEXT
	relay_fr_ip     TEXT
	relay_fr_fqdn   TEXT
	relay_to_ip     TEXT
	relay_to_fqdn   TEXT
        dsn             TEXT
        msgid           TEXT
	stat            TEXT

debug info by default is written to LOG_MAIL

=head1 OPTIONS

=over 4

=item B<-l> or B<--logfile> I<FILE>

sendmail log file to process. default is /var/log/maillog

=item B<-s> or B<--saveto> I<DIR>

directory to save db file to. by default it is the same as directory
of maillog file.

=item B<-e> or B<--export> I<FORMAT>

    sqlite - write to sqlite db

    raw    - raw internal structure dump (the
             same structure is dumped with verbosity > 3)

=item B<-v>

verbosity level (and will be incremented by 1 every time it appears on
the command line.)

=item B<-n> or B<--dry-run>

dry run

=back

=cut

=head1 EXAMPLE

=head3 select all statistics for mail recipient on 19700101

sqlite3 maillog-19700101-v19700101000000.sqlite 'SELECT * FROM maillog WHERE addr_to="jdoe@foo.bar"'

=head3 process all maillog* files

find /var/log -name "maillog.*" | xargs -I % /usr/local/bin/mailstate -l % -e sqlite

=head3 process one single maillog file

mailstate -e sqlite -s /var/db/mailstate/host01 -l /var/log/smarthosts/host01/host01.log -v

=head1 TODO

if it could ever be needed

INSERT OR REPLACE INTO to_addr_unique VALUES ( "foo@bar", coalesce( (SELECT to_addr_count FROM to_addr_unique WHERE to_addr_unique = "foo@bar"), 0) + 1);

=head1 SEE ALSO

sendmail(8), sqlite3(1), syslog(3), syslogd(8)

=head1 AUTHOR

Zeus Panchenko
